### ISSUE TITLE
fatal error: event/goEvent.h: No such file or directory

### ISSUE THREAD

**Issue by shardyr** [go-vgo/robotgo#521]
- Robotgo version (or commit ref): `v0.100.10`
- Go version: `go1.18.3`
- Gcc version: `11.1.0`
- Operating system and bit: Windows 10 64 bit
- Resolution: 1920x1080
- Can you reproduce the bug at [Examples](https://github.com/go-vgo/robotgo/blob/master/examples/main.go):
  - [x] Yes (provide example code)
  - [ ] No
  - [ ] Not relevant
- Provide example code:

```Go
package main

import (
	"github.com/go-vgo/robotgo"
)

func main() {
	robotgo.Click("right")
}
```
- Log gist:
```
$ go run .
# github.com/robotn/gohook
vendor\github.com\robotn\gohook\hook.go:22:10: fatal error: event/goEvent.h: No such file or directory
   22 | #include "event/goEvent.h"
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
```
## Description
After running `go mod vendor` I get this error. I tried fixing it by using this https://github.com/go-vgo/robotgo/issues/174#issuecomment-686369737 but it didn't work.

**Comment by svirmi** [comment]
@shardyr hello!
In my case (I am using xubuntu), the problem was with installing/updating dependencies command -
`sudo apt install libx11-dev xorg-dev libxtst-dev libpng++-dev`
 Software updater was set to fetch OS packages from local country server but there were missing or outdated packages.
After I set it to Main server , all required packages were downloaded and installed properly and the error gone

**Comment by huizhang001** [comment]
@shardyr Hello, have you resolved it. I used the modvendor method on the Windows system and still couldn't solve my problem？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？
